function imageFiles = getImgFiles()
    [f,p,~] = uigetfile({'*.png;*.jpg;*.bmp;*.tif','Supported images';...
                 '*.png','Portable Network Graphics (*.png)';...
                 '*.jpg','J-PEG (*.jpg)';...
                 '*.bmp','Bitmap (*.bmp)';...
                 '*.tif','Tagged Image File (*.tif,)';...
                 '*.*','All files (*.*)'},...
                 'MultiSelect', 'on');
     imageFiles = cell(1,numel(f));
     for i=1:numel(f)
         imageFiles{i} = strcat(p,f{i});
     end
end